server:
  port: 9002

spring:
  security:
    oauth2:
      client:
        registration:
          msgraph:
            provider:                     "msgraph"
            client-name:                  "Microsoft"
            client-id:                    "[env]"
            client-secret:                "[env]"
            authorization-grant-type:     "authorization_code"
            client-authentication-method: "POST"
            redirect-uri:                 "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid 
              - profile 
              - email
        provider: 
          msgraph:
            authorization-uri:   "https://login.microsoftonline.com/common/oauth2/v2.0/authorize"
            token-uri:           "https://login.microsoftonline.com/common/oauth2/v2.0/token"
            jwk-set-uri:         "https://login.microsoftonline.com/common/discovery/v2.0/keys"
            user-info-uri:       "https://graph.microsoft.com/beta/me"
            user-name-attribute: "id"
            user-info-authentication-method: "GET"
logging:    level:    org.springframework.web.client.RestTemplate: DEBUG